/**
 * WASM module loader and interface.
 * Handles loading the compiled C++ code and provides a clean API for calling WASM functions.
 * Uses direct function calls instead of SharedArrayBuffer for GitHub Pages compatibility.
 */

export class WasmModule {
    constructor() {
        this.module = null;
        this.ready = false;
    }

    /**
     * Load the WASM module.
     * @param {string} modulePath - Path to the .js file generated by Emscripten
     * @returns {Promise<void>}
     */
    async load(modulePath) {
        try {
            // Load the Emscripten-generated script as a regular script tag first
            // This ensures the module is available globally
            await this.loadScript(modulePath);

            // The MODULARIZE option exports a factory function
            // Wait for createHandTrackingModule to be available
            const factory = window.createHandTrackingModule;

            if (typeof factory !== 'function') {
                throw new Error('createHandTrackingModule not found. Make sure hand_tracking.js is loaded correctly.');
            }

            // Call the factory to create the module instance
            this.module = await factory();

            // Check if module has the expected exports
            if (!this.module || typeof this.module._init !== 'function') {
                throw new Error('WASM module did not initialize correctly');
            }

            this.ready = true;
            console.log('WASM module loaded successfully');
            return this.module;

        } catch (error) {
            console.error('Failed to load WASM module:', error);
            throw error;
        }
    }

    /**
     * Helper to load a script dynamically.
     * @param {string} src - Script URL
     * @returns {Promise<void>}
     */
    loadScript(src) {
        return new Promise((resolve, reject) => {
            // Check if already loaded
            if (window.createHandTrackingModule) {
                resolve();
                return;
            }

            const script = document.createElement('script');
            script.src = src;
            script.type = 'text/javascript';
            script.onload = () => resolve();
            script.onerror = () => reject(new Error(`Failed to load script: ${src}`));
            document.head.appendChild(script);
        });
    }

    /**
     * Initialize the WASM module.
     * @param {string} canvasSelector - CSS selector for the canvas element
     * @returns {number} 0 on success, -1 on failure
     */
    init(canvasSelector = '#canvas') {
        if (!this.ready) {
            console.error('WASM module not loaded');
            return -1;
        }

        const result = this.module._init(canvasSelector);
        if (result === 0) {
            console.log('WASM module initialized');
        } else {
            console.error('WASM module initialization failed');
        }
        return result;
    }

    /**
     * Process a frame by passing data directly to WASM.
     * Uses writeArrayToMemory to copy frame and hand data to WASM heap.
     *
     * @param {Uint8ClampedArray} frameData - RGBA frame data
     * @param {number} width - Frame width
     * @param {number} height - Frame height
     * @param {Array} hands - Array of hand data from MediaPipe
     */
    processFrame(frameData, width, height, hands) {
        if (!this.ready) {
            console.error('WASM module not loaded');
            return;
        }

        const frameSize = width * height * 4;  // RGBA
        const handDataSize = hands.length * (21 * 3 * 4 + 8);  // Each hand: 21 keypoints * 3 coords * 4 bytes + confidence + handedness

        // Allocate memory in WASM heap for frame data
        const framePtr = this.module._malloc(frameSize);
        if (!framePtr) {
            console.error('Failed to allocate WASM memory for frame');
            return;
        }

        // Copy frame data to WASM heap (HEAPU8 is a Uint8Array, not a constructor)
        this.module.HEAPU8.set(frameData, framePtr);

        // Allocate memory for hand data
        let handDataPtr = 0;
        if (hands.length > 0) {
            handDataPtr = this.module._malloc(handDataSize);
            if (!handDataPtr) {
                console.error('Failed to allocate WASM memory for hand data');
                this.module._free(framePtr);
                return;
            }

            // Copy hand data to WASM heap
            let offset = 0;

            for (let i = 0; i < hands.length && i < 2; i++) {
                const hand = hands[i];

                // Write keypoints (21 keypoints * 3 coords * 4 bytes)
                const kpHeap = new Float32Array(this.module.HEAPU8.buffer, handDataPtr + offset, 21 * 3);
                for (let j = 0; j < 21; j++) {
                    if (j < hand.keypoints.length) {
                        kpHeap[j * 3 + 0] = hand.keypoints[j][0];  // x
                        kpHeap[j * 3 + 1] = hand.keypoints[j][1];  // y
                        kpHeap[j * 3 + 2] = hand.keypoints[j][2];  // z
                    }
                }
                offset += 21 * 3 * 4;

                // Write confidence
                const confHeap = new Float32Array(this.module.HEAPU8.buffer, handDataPtr + offset, 1);
                confHeap[0] = hand.confidence || 1.0;
                offset += 4;

                // Write handedness
                this.module.HEAPU8[handDataPtr + offset] = hand.handedness ?? 255;
                offset += 4;  // 3 bytes padding
            }
        }

        // Call the WASM processFrame function
        this.module._processFrame(framePtr, width, height, handDataPtr, hands.length);

        // Free allocated memory
        this.module._free(framePtr);
        if (handDataPtr) {
            this.module._free(handDataPtr);
        }
    }

    /**
     * Clean up WASM resources.
     */
    cleanup() {
        if (!this.ready) {
            return;
        }
        this.module._cleanup();
        console.log('WASM module cleaned up');
    }

    /**
     * Check if the module is ready.
     * @returns {boolean}
     */
    isReady() {
        return this.ready;
    }
}
